[build]
target = [
    ## Windows
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",

    ## Apple
    "aarch64-apple-darwin",
    "aarch64-apple-ios", 
    "aarch64-apple-ios-sim",
    "x86_64-apple-darwin",

    ## Android

] 