# [build.'cfg(target_os="macos")']
# target = [
#     "aarch64-apple-darwin"
#     , "aarch64-apple-ios"
#     , "aarch64-apple-ios-sim"
# ] 

[build.'cfg(target_os="windows")']
target = [
    "i686-pc-windows-msvc"
    , "x86_64-pc-windows-msvc"
    , "aarch64-pc-windows-msvc"
] 